In [2]:
!pip install pymongo

Requirement already satisfied: pymongo in /usr/local/lib/python3.12/dist-packages (4.16.0)
Requirement already satisfied: dnspython<3.0.0,>=2.6.1 in /usr/local/lib/python3.12/dist-packages (from pymongo) (2.8.0)

In [3]:
import pymongo
from pymongo import MongoClient
import urllib.parse
from bson.json_util import dumps

In [4]:
url = "mongodb+srv://Nour:nour123@cluster0.ehpz3hf.mongodb.net/?retryWrites=true&w=majority"
cluster0 = MongoClient(url)

In [5]:
db = cluster0["kickstarterDB"]
collection = db["projects"]

In [6]:
import pandas as pd

df = pd.read_csv("kick_starter.csv", encoding='latin-1')

In [7]:
data =df.to_dict("records")
collection.insert_many(data)

InsertManyResult([ObjectId('69b57f64f97ba72a25a23441'), ObjectId('69b57f64f97ba72a25a23442'), ObjectId('69b57f64f97ba72a25a23443'), ObjectId('69b57f64f97ba72a25a23444'), ObjectId('69b57f64f97ba72a25a23445'), ObjectId('69b57f64f97ba72a25a23446'), ObjectId('69b57f64f97ba72a25a23447'), ObjectId('69b57f64f97ba72a25a23448'), ObjectId('69b57f64f97ba72a25a23449'), ObjectId('69b57f64f97ba72a25a2344a'), ObjectId('69b57f64f97ba72a25a2344b'), ObjectId('69b57f64f97ba72a25a2344c'), ObjectId('69b57f64f97ba72a25a2344d'), ObjectId('69b57f64f97ba72a25a2344e'), ObjectId('69b57f64f97ba72a25a2344f'), ObjectId('69b57f64f97ba72a25a23450'), ObjectId('69b57f64f97ba72a25a23451'), ObjectId('69b57f64f97ba72a25a23452'), ObjectId('69b57f64f97ba72a25a23453'), ObjectId('69b57f64f97ba72a25a23454'), ObjectId('69b57f64f97ba72a25a23455'), ObjectId('69b57f64f97ba72a25a23456'), ObjectId('69b57f64f97ba72a25a23457'), ObjectId('69b57f64f97ba72a25a23458'), ObjectId('69b57f64f97ba72a25a23459'), ObjectId('69b57f64f97ba72a25a2345a'), ObjectId('69b57f64f97ba72a25a2345b'), ObjectId('69b57f64f97ba72a25a2345c'), ObjectId('69b57f64f97ba72a25a2345d'), ObjectId('69b57f64f97ba72a25a2345e'), ObjectId('69b57f64f97ba72a25a2345f'), ObjectId('69b57f64f97ba72a25a23460'), ObjectId('69b57f64f97ba72a25a23461'), ObjectId('69b57f64f97ba72a25a23462'), ObjectId('69b57f64f97ba72a25a23463'), ObjectId('69b57f64f97ba72a25a23464'), ObjectId('69b57f64f97ba72a25a23465'), ObjectId('69b57f64f97ba72a25a23466'), ObjectId('69b57f64f97ba72a25a23467'), ObjectId('69b57f64f97ba72a25a23468'), ObjectId('69b57f64f97ba72a25a23469'), ObjectId('69b57f64f97ba72a25a2346a'), ObjectId('69b57f64f97ba72a25a2346b'), ObjectId('69b57f64f97ba72a25a2346c'), ObjectId('69b57f64f97ba72a25a2346d'), ObjectId('69b57f64f97ba72a25a2346e'), ObjectId('69b57f64f97ba72a25a2346f'), ObjectId('69b57f64f97ba72a25a23470'), ObjectId('69b57f64f97ba72a25a23471'), ObjectId('69b57f64f97ba72a25a23472'), ObjectId('69b57f64f97ba72a25a23473'), ObjectId('69b57f64f97ba72a25a23474'), ObjectId('69b57f64f97ba72a25a23475'), ObjectId('69b57f64f97ba72a25a23476'), ObjectId('69b57f64f97ba72a25a23477'), ObjectId('69b57f64f97ba72a25a23478'), ObjectId('69b57f64f97ba72a25a23479'), ObjectId('69b57f64f97ba72a25a2347a'), ObjectId('69b57f64f97ba72a25a2347b'), ObjectId('69b57f64f97ba72a25a2347c'), ObjectId('69b57f64f97ba72a25a2347d'), ObjectId('69b57f64f97ba72a25a2347e'), ObjectId('69b57f64f97ba72a25a2347f'), ObjectId('69b57f64f97ba72a25a23480'), ObjectId('69b57f64f97ba72a25a23481'), ObjectId('69b57f64f97ba72a25a23482'), ObjectId('69b57f64f97ba72a25a23483'), ObjectId('69b57f64f97ba72a25a23484'), ObjectId('69b57f64f97ba72a25a23485'), ObjectId('69b57f64f97ba72a25a23486'), ObjectId('69b57f64f97ba72a25a23487'), ObjectId('69b57f64f97ba72a25a23488'), ObjectId('69b57f64f97ba72a25a23489'), ObjectId('69b57f64f97ba72a25a2348a'), ObjectId('69b57f64f97ba72a25a2348b'), ObjectId('69b57f64f97ba72a25a2348c'), ObjectId('69b57f64f97ba72a25a2348d'), ObjectId('69b57f64f97ba72a25a2348e'), ObjectId('69b57f64f97ba72a25a2348f'), ObjectId('69b57f64f97ba72a25a23490'), ObjectId('69b57f64f97ba72a25a23491'), ObjectId('69b57f64f97ba72a25a23492'), ObjectId('69b57f64f97ba72a25a23493'), ObjectId('69b57f64f97ba72a25a23494'), ObjectId('69b57f64f97ba72a25a23495'), ObjectId('69b57f64f97ba72a25a23496'), ObjectId('69b57f64f97ba72a25a23497'), ObjectId('69b57f64f97ba72a25a23498'), ObjectId('69b57f64f97ba72a25a23499'), ObjectId('69b57f64f97ba72a25a2349a'), ObjectId('69b57f64f97ba72a25a2349b'), ObjectId('69b57f64f97ba72a25a2349c'), ObjectId('69b57f64f97ba72a25a2349d'), ObjectId('69b57f64f97ba72a25a2349e'), ObjectId('69b57f64f97ba72a25a2349f'), ObjectId('69b57f64f97ba72a25a234a0'), ObjectId('69b57f64f97ba72a25a234a1'), ObjectId('69b57f64f97ba72a25a234a2'), ObjectId('69b57f64f97ba72a25a234a3'), ObjectId('69b57f64f97ba72a25a234a4'), ObjectId('69b57f64f97ba72a25a234a5'), ObjectId('69b57f64f97ba72a25a234a6'), ObjectId('69b57f64f97ba72a25a234a7'), ObjectId('69b57f64f97ba72a25a234a8'), ObjectId('69b57f64f97ba72a25a234a9'), ObjectId('69b57f64f97ba72a25a234aa'), ObjectId('69b57f64f97ba72a25a234ab'), ObjectId('69b57f64f97ba72a25a234ac'), ObjectId('69b57f64f97ba72a25a234ad'), ObjectId('69b57f64f97ba72a25a234ae'), ObjectId('69b57f64f97ba72a25a234af'), ObjectId('69b57f64f97ba72a25a234b0'), ObjectId('69b57f64f97ba72a25a234b1'), ObjectId('69b57f64f97ba72a25a234b2'), ObjectId('69b57f64f97ba72a25a234b3'), ObjectId('69b57f64f97ba72a25a234b4'), ObjectId('69b57f64f97ba72a25a234b5'), ObjectId('69b57f64f97ba72a25a234b6'), ObjectId('69b57f64f97ba72a25a234b7'), ObjectId('69b57f64f97ba72a25a234b8'), ObjectId('69b57f64f97ba72a25a234b9'), ObjectId('69b57f64f97ba72a25a234ba'), ObjectId('69b57f64f97ba72a25a234bb'), ObjectId('69b57f64f97ba72a25a234bc'), ObjectId('69b57f64f97ba72a25a234bd'), ObjectId('69b57f64f97ba72a25a234be'), ObjectId('69b57f64f97ba72a25a234bf'), ObjectId('69b57f64f97ba72a25a234c0'), ObjectId('69b57f64f97ba72a25a234c1'), ObjectId('69b57f64f97ba72a25a234c2'), ObjectId('69b57f64f97ba72a25a234c3'), ObjectId('69b57f64f97ba72a25a234c4'), ObjectId('69b57f64f97ba72a25a234c5'), ObjectId('69b57f64f97ba72a25a234c6'), ObjectId('69b57f64f97ba72a25a234c7'), ObjectId('69b57f64f97ba72a25a234c8'), ObjectId('69b57f64f97ba72a25a234c9'), ObjectId('69b57f64f97ba72a25a234ca'), ObjectId('69b57f64f97ba72a25a234cb'), ObjectId('69b57f64f97ba72a25a234cc'), ObjectId('69b57f64f97ba72a25a234cd'), ObjectId('69b57f64f97ba72a25a234ce'), ObjectId('69b57f64f97ba72a25a234cf'), ObjectId('69b57f64f97ba72a25a234d0'), ObjectId('69b57f64f97ba72a25a234d1'), ObjectId('69b57f64f97ba72a25a234d2'), ObjectId('69b57f64f97ba72a25a234d3'), ObjectId('69b57f64f97ba72a25a234d4'), ObjectId('69b57f64f97ba72a25a234d5'), ObjectId('69b57f64f97ba72a25a234d6'), ObjectId('69b57f64f97ba72a25a234d7'), ObjectId('69b57f64f97ba72a25a234d8'), ObjectId('69b57f64f97ba72a25a234d9'), ObjectId('69b57f64f97ba72a25a234da'), ObjectId('69b57f64f97ba72a25a234db'), ObjectId('69b57f64f97ba72a25a234dc'), ObjectId('69b57f64f97ba72a25a234dd'), ObjectId('69b57f64f97ba72a25a234de'), ObjectId('69b57f64f97ba72a25a234df'), ObjectId('69b57f64f97ba72a25a234e0'), ObjectId('69b57f64f97ba72a25a234e1'), ObjectId('69b57f64f97ba72a25a234e2'), ObjectId('69b57f64f97ba72a25a234e3'), ObjectId('69b57f64f97ba72a25a234e4'), ObjectId('69b57f64f97ba72a25a234e5'), ObjectId('69b57f64f97ba72a25a234e6'), ObjectId('69b57f64f97ba72a25a234e7'), ObjectId('69b57f64f97ba72a25a234e8'), ObjectId('69b57f64f97ba72a25a234e9'), ObjectId('69b57f64f97ba72a25a234ea'), ObjectId('69b57f64f97ba72a25a234eb'), ObjectId('69b57f64f97ba72a25a234ec'), ObjectId('69b57f64f97ba72a25a234ed'), ObjectId('69b57f64f97ba72a25a234ee'), ObjectId('69b57f64f97ba72a25a234ef'), ObjectId('69b57f64f97ba72a25a234f0'), ObjectId('69b57f64f97ba72a25a234f1'), ObjectId('69b57f64f97ba72a25a234f2'), ObjectId('69b57f64f97ba72a25a234f3'), ObjectId('69b57f64f97ba72a25a234f4'), ObjectId('69b57f64f97ba72a25a234f5'), ObjectId('69b57f64f97ba72a25a234f6'), ObjectId('69b57f64f97ba72a25a234f7'), ObjectId('69b57f64f97ba72a25a234f8'), ObjectId('69b57f64f97ba72a25a234f9'), ObjectId('69b57f64f97ba72a25a234fa'), ObjectId('69b57f64f97ba72a25a234fb'), ObjectId('69b57f64f97ba72a25a234fc'), ObjectId('69b57f64f97ba72a25a234fd'), ObjectId('69b57f64f97ba72a25a234fe'), ObjectId('69b57f64f97ba72a25a234ff'), ObjectId('69b57f64f97ba72a25a23500'), ObjectId('69b57f64f97ba72a25a23501'), ObjectId('69b57f64f97ba72a25a23502'), ObjectId('69b57f64f97ba72a25a23503'), ObjectId('69b57f64f97ba72a25a23504'), ObjectId('69b57f64f97ba72a25a23505'), ObjectId('69b57f64f97ba72a25a23506'), ObjectId('69b57f64f97ba72a25a23507'), ObjectId('69b57f64f97ba72a25a23508'), ObjectId('69b57f64f97ba72a25a23509'), ObjectId('69b57f64f97ba72a25a2350a'), ObjectId('69b57f64f97ba72a25a2350b'), ObjectId('69b57f64f97ba72a25a2350c'), ObjectId('69b57f64f97ba72a25a2350d'), ObjectId('69b57f64f97ba72a25a2350e'), ObjectId('69b57f64f97ba72a25a2350f'), ObjectId('69b57f64f97ba72a25a23510'), ObjectId('69b57f64f97ba72a25a23511'), ObjectId('69b57f64f97ba72a25a23512'), ObjectId('69b57f64f97ba72a25a23513'), ObjectId('69b57f64f97ba72a25a23514'), ObjectId('69b57f64f97ba72a25a23515'), ObjectId('69b57f64f97ba72a25a23516'), ObjectId('69b57f64f97ba72a25a23517'), ObjectId('69b57f64f97ba72a25a23518'), ObjectId('69b57f64f97ba72a25a23519'), ObjectId('69b57f64f97ba72a25a2351a'), ObjectId('69b57f64f97ba72a25a2351b'), ObjectId('69b57f64f97ba72a25a2351c'), ObjectId('69b57f64f97ba72a25a2351d'), ObjectId('69b57f64f97ba72a25a2351e'), ObjectId('69b57f64f97ba72a25a2351f'), ObjectId('69b57f64f97ba72a25a23520'), ObjectId('69b57f64f97ba72a25a23521'), ObjectId('69b57f64f97ba72a25a23522'), ObjectId('69b57f64f97ba72a25a23523'), ObjectId('69b57f64f97ba72a25a23524'), ObjectId('69b57f64f97ba72a25a23525'), ObjectId('69b57f64f97ba72a25a23526'), ObjectId('69b57f64f97ba72a25a23527'), ObjectId('69b57f64f97ba72a25a23528'), ObjectId('69b57f64f97ba72a25a23529'), ObjectId('69b57f64f97ba72a25a2352a'), ObjectId('69b57f64f97ba72a25a2352b'), ObjectId('69b57f64f97ba72a25a2352c'), ObjectId('69b57f64f97ba72a25a2352d'), ObjectId('69b57f64f97ba72a25a2352e'), ObjectId('69b57f64f97ba72a25a2352f'), ObjectId('69b57f64f97ba72a25a23530'), ObjectId('69b57f64f97ba72a25a23531'), ObjectId('69b57f64f97ba72a25a23532'), ObjectId('69b57f64f97ba72a25a23533'), ObjectId('69b57f64f97ba72a25a23534'), ObjectId('69b57f64f97ba72a25a23535'), ObjectId('69b57f64f97ba72a25a23536'), ObjectId('69b57f64f97ba72a25a23537'), ObjectId('69b57f64f97ba72a25a23538'), ObjectId('69b57f64f97ba72a25a23539'), ObjectId('69b57f64f97ba72a25a2353a'), ObjectId('69b57f64f97ba72a25a2353b'), ObjectId('69b57f64f97ba72a25a2353c'), ObjectId('69b57f64f97ba72a25a2353d'), ObjectId('69b57f64f97ba72a25a2353e'), ObjectId('69b57f64f97ba72a25a2353f'), ObjectId('69b57f64f97ba72a25a23540'), ObjectId('69b57f64f97ba72a25a23541'), ObjectId('69b57f64f97ba72a25a23542'), ObjectId('69b57f64f97ba72a25a23543'), ObjectId('69b57f64f97ba72a25a23544'), ObjectId('69b57f64f97ba72a25a23545'), ObjectId('69b57f64f97ba72a25a23546'), ObjectId('69b57f64f97ba72a25a23547'), ObjectId('69b57f64f97ba72a25a23548'), ObjectId('69b57f64f97ba72a25a23549'), ObjectId('69b57f64f97ba72a25a2354a'), ObjectId('69b57f64f97ba72a25a2354b'), ObjectId('69b57f64f97ba72a25a2354c'), ObjectId('69b57f64f97ba72a25a2354d'), ObjectId('69b57f64f97ba72a25a2354e'), ObjectId('69b57f64f97ba72a25a2354f'), ObjectId('69b57f64f97ba72a25a23550'), ObjectId('69b57f64f97ba72a25a23551'), ObjectId('69b57f64f97ba72a25a23552'), ObjectId('69b57f64f97ba72a25a23553'), ObjectId('69b57f64f97ba72a25a23554'), ObjectId('69b57f64f97ba72a25a23555'), ObjectId('69b57f64f97ba72a25a23556'), ObjectId('69b57f64f97ba72a25a23557'), ObjectId('69b57f64f97ba72a25a23558'), ObjectId('69b57f64f97ba72a25a23559'), ObjectId('69b57f64f97ba72a25a2355a'), ObjectId('69b57f64f97ba72a25a2355b'), ObjectId('69b57f64f97ba72a25a2355c'), ObjectId('69b57f64f97ba72a25a2355d'), ObjectId('69b57f64f97ba72a25a2355e'), ObjectId('69b57f64f97ba72a25a2355f'), ObjectId('69b57f64f97ba72a25a23560'), ObjectId('69b57f64f97ba72a25a23561'), ObjectId('69b57f64f97ba72a25a23562'), ObjectId('69b57f64f97ba72a25a23563'), ObjectId('69b57f64f97ba72a25a23564'), ObjectId('69b57f64f97ba72a25a23565'), ObjectId('69b57f64f97ba72a25a23566'), ObjectId('69b57f64f97ba72a25a23567'), ObjectId('69b57f64f97ba72a25a23568'), ObjectId('69b57f64f97ba72a25a23569'), ObjectId('69b57f64f97ba72a25a2356a'), ObjectId('69b57f64f97ba72a25a2356b'), ObjectId('69b57f64f97ba72a25a2356c'), ObjectId('69b57f64f97ba72a25a2356d'), ObjectId('69b57f64f97ba72a25a2356e'), ObjectId('69b57f64f97ba72a25a2356f'), ObjectId('69b57f64f97ba72a25a23570'), ObjectId('69b57f64f97ba72a25a23571'), ObjectId('69b57f64f97ba72a25a23572'), ObjectId('69b57f64f97ba72a25a23573'), ObjectId('69b57f64f97ba72a25a23574'), ObjectId('69b57f64f97ba72a25a23575'), ObjectId('69b57f64f97ba72a25a23576'), ObjectId('69b57f64f97ba72a25a23577'), ObjectId('69b57f64f97ba72a25a23578'), ObjectId('69b57f64f97ba72a25a23579'), ObjectId('69b57f64f97ba72a25a2357a'), ObjectId('69b57f64f97ba72a25a2357b'), ObjectId('69b57f64f97ba72a25a2357c'), ObjectId('69b57f64f97ba72a25a2357d'), ObjectId('69b57f64f97ba72a25a2357e'), ObjectId('69b57f64f97ba72a25a2357f'), ObjectId('69b57f64f97ba72a25a23580'), ObjectId('69b57f64f97ba72a25a23581'), ObjectId('69b57f64f97ba72a25a23582'), ObjectId('69b57f64f97ba72a25a23583'), ObjectId('69b57f64f97ba72a25a23584'), ObjectId('69b57f64f97ba72a25a23585'), ObjectId('69b57f64f97ba72a25a23586'), ObjectId('69b57f64f97ba72a25a23587'), ObjectId('69b57f64f97ba72a25a23588'), ObjectId('69b57f64f97ba72a25a23589'), ObjectId('69b57f64f97ba72a25a2358a'), ObjectId('69b57f64f97ba72a25a2358b'), ObjectId('69b57f64f97ba72a25a2358c'), ObjectId('69b57f64f97ba72a25a2358d'), ObjectId('69b57f64f97ba72a25a2358e'), ObjectId('69b57f64f97ba72a25a2358f'), ObjectId('69b57f64f97ba72a25a23590'), ObjectId('69b57f64f97ba72a25a23591'), ObjectId('69b57f64f97ba72a25a23592'), ObjectId('69b57f64f97ba72a25a23593'), ObjectId('69b57f64f97ba72a25a23594'), ObjectId('69b57f64f97ba72a25a23595'), ObjectId('69b57f64f97ba72a25a23596'), ObjectId('69b57f64f97ba72a25a23597'), ObjectId('69b57f64f97ba72a25a23598'), ObjectId('69b57f64f97ba72a25a23599'), ObjectId('69b57f64f97ba72a25a2359a'), ObjectId('69b57f64f97ba72a25a2359b'), ObjectId('69b57f64f97ba72a25a2359c'), ObjectId('69b57f64f97ba72a25a2359d'), ObjectId('69b57f64f97ba72a25a2359e'), ObjectId('69b57f64f97ba72a25a2359f'), ObjectId('69b57f64f97ba72a25a235a0'), ObjectId('69b57f64f97ba72a25a235a1'), ObjectId('69b57f64f97ba72a25a235a2'), ObjectId('69b57f64f97ba72a25a235a3'), ObjectId('69b57f64f97ba72a25a235a4'), ObjectId('69b57f64f97ba72a25a235a5'), ObjectId('69b57f64f97ba72a25a235a6'), ObjectId('69b57f64f97ba72a25a235a7'), ObjectId('69b57f64f97ba72a25a235a8'), ObjectId('69b57f64f97ba72a25a235a9'), ObjectId('69b57f64f97ba72a25a235aa'), ObjectId('69b57f64f97ba72a25a235ab'), ObjectId('69b57f64f97ba72a25a235ac'), ObjectId('69b57f64f97ba72a25a235ad'), ObjectId('69b57f64f97ba72a25a235ae'), ObjectId('69b57f64f97ba72a25a235af'), ObjectId('69b57f64f97ba72a25a235b0'), ObjectId('69b57f64f97ba72a25a235b1'), ObjectId('69b57f64f97ba72a25a235b2'), ObjectId('69b57f64f97ba72a25a235b3'), ObjectId('69b57f64f97ba72a25a235b4'), ObjectId('69b57f64f97ba72a25a235b5'), ObjectId('69b57f64f97ba72a25a235b6'), ObjectId('69b57f64f97ba72a25a235b7'), ObjectId('69b57f64f97ba72a25a235b8'), ObjectId('69b57f64f97ba72a25a235b9'), ObjectId('69b57f64f97ba72a25a235ba'), ObjectId('69b57f64f97ba72a25a235bb'), ObjectId('69b57f64f97ba72a25a235bc'), ObjectId('69b57f64f97ba72a25a235bd'), ObjectId('69b57f64f97ba72a25a235be'), ObjectId('69b57f64f97ba72a25a235bf'), ObjectId('69b57f64f97ba72a25a235c0'), ObjectId('69b57f64f97ba72a25a235c1'), ObjectId('69b57f64f97ba72a25a235c2'), ObjectId('69b57f64f97ba72a25a235c3'), ObjectId('69b57f64f97ba72a25a235c4'), ObjectId('69b57f64f97ba72a25a235c5'), ObjectId('69b57f64f97ba72a25a235c6'), ObjectId('69b57f64f97ba72a25a235c7'), ObjectId('69b57f64f97ba72a25a235c8'), ObjectId('69b57f64f97ba72a25a235c9'), ObjectId('69b57f64f97ba72a25a235ca'), ObjectId('69b57f64f97ba72a25a235cb'), ObjectId('69b57f64f97ba72a25a235cc'), ObjectId('69b57f64f97ba72a25a235cd'), ObjectId('69b57f64f97ba72a25a235ce'), ObjectId('69b57f64f97ba72a25a235cf'), ObjectId('69b57f64f97ba72a25a235d0'), ObjectId('69b57f64f97ba72a25a235d1'), ObjectId('69b57f64f97ba72a25a235d2'), ObjectId('69b57f64f97ba72a25a235d3'), ObjectId('69b57f64f97ba72a25a235d4'), ObjectId('69b57f64f97ba72a25a235d5'), ObjectId('69b57f64f97ba72a25a235d6'), ObjectId('69b57f64f97ba72a25a235d7'), ObjectId('69b57f64f97ba72a25a235d8'), ObjectId('69b57f64f97ba72a25a235d9'), ObjectId('69b57f64f97ba72a25a235da'), ObjectId('69b57f64f97ba72a25a235db'), ObjectId('69b57f64f97ba72a25a235dc'), ObjectId('69b57f64f97ba72a25a235dd'), ObjectId('69b57f64f97ba72a25a235de'), ObjectId('69b57f64f97ba72a25a235df'), ObjectId('69b57f64f97ba72a25a235e0'), ObjectId('69b57f64f97ba72a25a235e1'), ObjectId('69b57f64f97ba72a25a235e2'), ObjectId('69b57f64f97ba72a25a235e3'), ObjectId('69b57f64f97ba72a25a235e4'), ObjectId('69b57f64f97ba72a25a235e5'), ObjectId('69b57f64f97ba72a25a235e6'), ObjectId('69b57f64f97ba72a25a235e7'), ObjectId('69b57f64f97ba72a25a235e8'), ObjectId('69b57f64f97ba72a25a235e9'), ObjectId('69b57f64f97ba72a25a235ea'), ObjectId('69b57f64f97ba72a25a235eb'), ObjectId('69b57f64f97ba72a25a235ec'), ObjectId('69b57f64f97ba72a25a235ed'), ObjectId('69b57f64f97ba72a25a235ee'), ObjectId('69b57f64f97ba72a25a235ef'), ObjectId('69b57f64f97ba72a25a235f0'), ObjectId('69b57f64f97ba72a25a235f1'), ObjectId('69b57f64f97ba72a25a235f2'), ObjectId('69b57f64f97ba72a25a235f3'), ObjectId('69b57f64f97ba72a25a235f4'), ObjectId('69b57f64f97ba72a25a235f5'), ObjectId('69b57f64f97ba72a25a235f6'), ObjectId('69b57f64f97ba72a25a235f7'), ObjectId('69b57f64f97ba72a25a235f8'), ObjectId('69b57f64f97ba72a25a235f9'), ObjectId('69b57f64f97ba72a25a235fa'), ObjectId('69b57f64f97ba72a25a235fb'), ObjectId('69b57f64f97ba72a25a235fc'), ObjectId('69b57f64f97ba72a25a235fd'), ObjectId('69b57f64f97ba72a25a235fe'), ObjectId('69b57f64f97ba72a25a235ff'), ObjectId('69b57f64f97ba72a25a23600'), ObjectId('69b57f64f97ba72a25a23601'), ObjectId('69b57f64f97ba72a25a23602'), ObjectId('69b57f64f97ba72a25a23603'), ObjectId('69b57f64f97ba72a25a23604'), ObjectId('69b57f64f97ba72a25a23605'), ObjectId('69b57f64f97ba72a25a23606'), ObjectId('69b57f64f97ba72a25a23607'), ObjectId('69b57f64f97ba72a25a23608'), ObjectId('69b57f64f97ba72a25a23609'), ObjectId('69b57f64f97ba72a25a2360a'), ObjectId('69b57f64f97ba72a25a2360b'), ObjectId('69b57f64f97ba72a25a2360c'), ObjectId('69b57f64f97ba72a25a2360d'), ObjectId('69b57f64f97ba72a25a2360e'), ObjectId('69b57f64f97ba72a25a2360f'), ObjectId('69b57f64f97ba72a25a23610'), ObjectId('69b57f64f97ba72a25a23611'), ObjectId('69b57f64f97ba72a25a23612'), ObjectId('69b57f64f97ba72a25a23613'), ObjectId('69b57f64f97ba72a25a23614'), ObjectId('69b57f64f97ba72a25a23615'), ObjectId('69b57f64f97ba72a25a23616'), ObjectId('69b57f64f97ba72a25a23617'), ObjectId('69b57f64f97ba72a25a23618'), ObjectId('69b57f64f97ba72a25a23619'), ObjectId('69b57f64f97ba72a25a2361a'), ObjectId('69b57f64f97ba72a25a2361b'), ObjectId('69b57f64f97ba72a25a2361c'), ObjectId('69b57f64f97ba72a25a2361d'), ObjectId('69b57f64f97ba72a25a2361e'), ObjectId('69b57f64f97ba72a25a2361f'), ObjectId('69b57f64f97ba72a25a23620'), ObjectId('69b57f64f97ba72a25a23621'), ObjectId('69b57f64f97ba72a25a23622'), ObjectId('69b57f64f97ba72a25a23623'), ObjectId('69b57f64f97ba72a25a23624'), ObjectId('69b57f64f97ba72a25a23625'), ObjectId('69b57f64f97ba72a25a23626'), ObjectId('69b57f64f97ba72a25a23627'), ObjectId('69b57f64f97ba72a25a23628'), ObjectId('69b57f64f97ba72a25a23629'), ObjectId('69b57f64f97ba72a25a2362a'), ObjectId('69b57f64f97ba72a25a2362b'), ObjectId('69b57f64f97ba72a25a2362c'), ObjectId('69b57f64f97ba72a25a2362d'), ObjectId('69b57f64f97ba72a25a2362e'), ObjectId('69b57f64f97ba72a25a2362f'), ObjectId('69b57f64f97ba72a25a23630'), ObjectId('69b57f64f97ba72a25a23631'), ObjectId('69b57f64f97ba72a25a23632'), ObjectId('69b57f64f97ba72a25a23633'), ObjectId('69b57f64f97ba72a25a23634'), ObjectId('69b57f64f97ba72a25a23635'), ObjectId('69b57f64f97ba72a25a23636'), ObjectId('69b57f64f97ba72a25a23637'), ObjectId('69b57f64f97ba72a25a23638'), ObjectId('69b57f64f97ba72a25a23639'), ObjectId('69b57f64f97ba72a25a2363a'), ObjectId('69b57f64f97ba72a25a2363b'), ObjectId('69b57f64f97ba72a25a2363c'), ObjectId('69b57f64f97ba72a25a2363d'), ObjectId('69b57f64f97ba72a25a2363e'), ObjectId('69b57f64f97ba72a25a2363f'), ObjectId('69b57f64f97ba72a25a23640'), ObjectId('69b57f64f97ba72a25a23641'), ObjectId('69b57f64f97ba72a25a23642'), ObjectId('69b57f64f97ba72a25a23643'), ObjectId('69b57f64f97ba72a25a23644'), ObjectId('69b57f64f97ba72a25a23645'), ObjectId('69b57f64f97ba72a25a23646'), ObjectId('69b57f64f97ba72a25a23647'), ObjectId('69b57f64f97ba72a25a23648'), ObjectId('69b57f64f97ba72a25a23649'), ObjectId('69b57f64f97ba72a25a2364a'), ObjectId('69b57f64f97ba72a25a2364b'), ObjectId('69b57f64f97ba72a25a2364c'), ObjectId('69b57f64f97ba72a25a2364d'), ObjectId('69b57f64f97ba72a25a236

In [8]:
df.isnull().sum()

ID                    0
name                  0
category              1
main_category         1
currency              1
deadline              1
goal                  1
launched              1
pledged               1
state                 1
backers               1
country               1
usd pledged         337
usd_pledged_real      1
usd_goal_real         1
dtype: int64

In [9]:
df = df.dropna()
df = df.drop_duplicates()
df = df[df["state"] != "live"]

In [10]:
df.isnull().sum()

ID                  0
name                0
category            0
main_category       0
currency            0
deadline            0
goal                0
launched            0
pledged             0
state               0
backers             0
country             0
usd pledged         0
usd_pledged_real    0
usd_goal_real       0
dtype: int64

In [11]:
df["launched"] = pd.to_datetime(df["launched"])
df["deadline"] = pd.to_datetime(df["deadline"])

In [12]:
df["CampaignDuration"] = (df["deadline"] - df["launched"]).dt.days
df[["launched","deadline","CampaignDuration"]].head()

             launched   deadline  CampaignDuration
0 2015-08-11 12:12:28 2015-10-09                58
1 2017-09-02 04:43:57 2017-11-01                59
2 2013-01-12 00:20:50 2013-02-26                44
3 2012-03-17 03:24:11 2012-04-16                29
4 2015-07-04 08:35:03 2015-08-29                55

In [13]:
df["FundingRatio"] = df["usd_pledged_real"] / df["usd_goal_real"]

In [14]:
def goal_category(goal):
    if goal < 10000:
        return "Low Goal"
    elif goal <= 100000:
        return "Medium Goal"
    else:
        return "High Goal"
df["GoalCategory"] = df["usd_goal_real"].apply(goal_category)

In [15]:
df["LaunchMonth"] = df["launched"].dt.month_name()

In [16]:
df.head()

,ID,name,category,main_category,currency,deadline,goal,launched,pledged,state,backers,country,usd pledged,usd_pledged_real,usd_goal_real,CampaignDuration,FundingRatio,GoalCategory,LaunchMonth
0,1000002330,The Songs of Adelaide & Abullah,Poetry,Publishing,GBP,2015-10-09,1000.0,2015-08-11 12:12:28,0.0,failed,0.0,GB,0.0,0.0,1533.95,58,0.000000,Low Goal,August
1,1000003930,Greeting From Earth: ZGAC Arts Capsule For ET,Narrative Film,Film & Video,USD,2017-11-01,30000.0,2017-09-02 04:43:57,2421.0,failed,15.0,US,100.0,2421.0,30000.00,59,0.080700,Medium Goal,September
2,1000004038,Where is Hank?,Narrative Film,Film & Video,USD,2013-02-26,45000.0,2013-01-12 00:20:50,220.0,failed,3.0,US,220.0,220.0,45000.00,44,0.004889,Medium Goal,January
3,1000007540,ToshiCapital Rekordz Needs Help to Complete Album,Music,Music,USD,2012-04-16,5000.0,2012-03-17 03:24:11,1.0,failed,1.0,US,1.0,1.0,5000.00,29,0.000200,Low Goal,March
4,1000011046,Community Film Project: The Art of Neighborhoo...,Film & Video,Film & Video,USD,2015-08-29,19500.0,2015-07-04 08:35:03,1283.0,canceled,14.0,US,1283.0,1283.0,19500.00,55,0.065795,Medium Goal,July

In [17]:
df[["CampaignDuration","FundingRatio","GoalCategory","LaunchMonth"]].head()

   CampaignDuration  FundingRatio GoalCategory LaunchMonth
0                58      0.000000     Low Goal      August
1                59      0.080700  Medium Goal   September
2                44      0.004889  Medium Goal     January
3                29      0.000200     Low Goal       March
4                55      0.065795  Medium Goal        July

In [18]:
collection.delete_many({})

DeleteResult({'n': 60863, 'electionId': ObjectId('7fffffff00000000000000d4'), 'opTime': {'ts': Timestamp(1773502329, 765), 't': 212}, 'ok': 1.0, '$clusterTime': {'clusterTime': Timestamp(1773502329, 765), 'signature': {'hash': b'\x10\xfd\xc6\xa4P\n\xc8\x08\xa2\xf7\x03\xe1\xf4\x06\x17\xc7\x8c\xac\xa4\x8d', 'keyId': 7573749362740690946}}, 'operationTime': Timestamp(1773502329, 765)}, acknowledged=True)

In [19]:
data = df.to_dict("records")
collection.insert_many(data)

InsertManyResult([ObjectId('69b57f7bf97ba72a25a2b970'), ObjectId('69b57f7bf97ba72a25a2b971'), ObjectId('69b57f7bf97ba72a25a2b972'), ObjectId('69b57f7bf97ba72a25a2b973'), ObjectId('69b57f7bf97ba72a25a2b974'), ObjectId('69b57f7bf97ba72a25a2b975'), ObjectId('69b57f7bf97ba72a25a2b976'), ObjectId('69b57f7bf97ba72a25a2b977'), ObjectId('69b57f7bf97ba72a25a2b978'), ObjectId('69b57f7bf97ba72a25a2b979'), ObjectId('69b57f7bf97ba72a25a2b97a'), ObjectId('69b57f7bf97ba72a25a2b97b'), ObjectId('69b57f7bf97ba72a25a2b97c'), ObjectId('69b57f7bf97ba72a25a2b97d'), ObjectId('69b57f7bf97ba72a25a2b97e'), ObjectId('69b57f7bf97ba72a25a2b97f'), ObjectId('69b57f7bf97ba72a25a2b980'), ObjectId('69b57f7bf97ba72a25a2b981'), ObjectId('69b57f7bf97ba72a25a2b982'), ObjectId('69b57f7bf97ba72a25a2b983'), ObjectId('69b57f7bf97ba72a25a2b984'), ObjectId('69b57f7bf97ba72a25a2b985'), ObjectId('69b57f7bf97ba72a25a2b986'), ObjectId('69b57f7bf97ba72a25a2b987'), ObjectId('69b57f7bf97ba72a25a2b988'), ObjectId('69b57f7bf97ba72a25a2b989'), ObjectId('69b57f7bf97ba72a25a2b98a'), ObjectId('69b57f7bf97ba72a25a2b98b'), ObjectId('69b57f7bf97ba72a25a2b98c'), ObjectId('69b57f7bf97ba72a25a2b98d'), ObjectId('69b57f7bf97ba72a25a2b98e'), ObjectId('69b57f7bf97ba72a25a2b98f'), ObjectId('69b57f7bf97ba72a25a2b990'), ObjectId('69b57f7bf97ba72a25a2b991'), ObjectId('69b57f7bf97ba72a25a2b992'), ObjectId('69b57f7bf97ba72a25a2b993'), ObjectId('69b57f7bf97ba72a25a2b994'), ObjectId('69b57f7bf97ba72a25a2b995'), ObjectId('69b57f7bf97ba72a25a2b996'), ObjectId('69b57f7bf97ba72a25a2b997'), ObjectId('69b57f7bf97ba72a25a2b998'), ObjectId('69b57f7bf97ba72a25a2b999'), ObjectId('69b57f7bf97ba72a25a2b99a'), ObjectId('69b57f7bf97ba72a25a2b99b'), ObjectId('69b57f7bf97ba72a25a2b99c'), ObjectId('69b57f7bf97ba72a25a2b99d'), ObjectId('69b57f7bf97ba72a25a2b99e'), ObjectId('69b57f7bf97ba72a25a2b99f'), ObjectId('69b57f7bf97ba72a25a2b9a0'), ObjectId('69b57f7bf97ba72a25a2b9a1'), ObjectId('69b57f7bf97ba72a25a2b9a2'), ObjectId('69b57f7bf97ba72a25a2b9a3'), ObjectId('69b57f7bf97ba72a25a2b9a4'), ObjectId('69b57f7bf97ba72a25a2b9a5'), ObjectId('69b57f7bf97ba72a25a2b9a6'), ObjectId('69b57f7bf97ba72a25a2b9a7'), ObjectId('69b57f7bf97ba72a25a2b9a8'), ObjectId('69b57f7bf97ba72a25a2b9a9'), ObjectId('69b57f7bf97ba72a25a2b9aa'), ObjectId('69b57f7bf97ba72a25a2b9ab'), ObjectId('69b57f7bf97ba72a25a2b9ac'), ObjectId('69b57f7bf97ba72a25a2b9ad'), ObjectId('69b57f7bf97ba72a25a2b9ae'), ObjectId('69b57f7bf97ba72a25a2b9af'), ObjectId('69b57f7bf97ba72a25a2b9b0'), ObjectId('69b57f7bf97ba72a25a2b9b1'), ObjectId('69b57f7bf97ba72a25a2b9b2'), ObjectId('69b57f7bf97ba72a25a2b9b3'), ObjectId('69b57f7bf97ba72a25a2b9b4'), ObjectId('69b57f7bf97ba72a25a2b9b5'), ObjectId('69b57f7bf97ba72a25a2b9b6'), ObjectId('69b57f7bf97ba72a25a2b9b7'), ObjectId('69b57f7bf97ba72a25a2b9b8'), ObjectId('69b57f7bf97ba72a25a2b9b9'), ObjectId('69b57f7bf97ba72a25a2b9ba'), ObjectId('69b57f7bf97ba72a25a2b9bb'), ObjectId('69b57f7bf97ba72a25a2b9bc'), ObjectId('69b57f7bf97ba72a25a2b9bd'), ObjectId('69b57f7bf97ba72a25a2b9be'), ObjectId('69b57f7bf97ba72a25a2b9bf'), ObjectId('69b57f7bf97ba72a25a2b9c0'), ObjectId('69b57f7bf97ba72a25a2b9c1'), ObjectId('69b57f7bf97ba72a25a2b9c2'), ObjectId('69b57f7bf97ba72a25a2b9c3'), ObjectId('69b57f7bf97ba72a25a2b9c4'), ObjectId('69b57f7bf97ba72a25a2b9c5'), ObjectId('69b57f7bf97ba72a25a2b9c6'), ObjectId('69b57f7bf97ba72a25a2b9c7'), ObjectId('69b57f7bf97ba72a25a2b9c8'), ObjectId('69b57f7bf97ba72a25a2b9c9'), ObjectId('69b57f7bf97ba72a25a2b9ca'), ObjectId('69b57f7bf97ba72a25a2b9cb'), ObjectId('69b57f7bf97ba72a25a2b9cc'), ObjectId('69b57f7bf97ba72a25a2b9cd'), ObjectId('69b57f7bf97ba72a25a2b9ce'), ObjectId('69b57f7bf97ba72a25a2b9cf'), ObjectId('69b57f7bf97ba72a25a2b9d0'), ObjectId('69b57f7bf97ba72a25a2b9d1'), ObjectId('69b57f7bf97ba72a25a2b9d2'), ObjectId('69b57f7bf97ba72a25a2b9d3'), ObjectId('69b57f7bf97ba72a25a2b9d4'), ObjectId('69b57f7bf97ba72a25a2b9d5'), ObjectId('69b57f7bf97ba72a25a2b9d6'), ObjectId('69b57f7bf97ba72a25a2b9d7'), ObjectId('69b57f7bf97ba72a25a2b9d8'), ObjectId('69b57f7bf97ba72a25a2b9d9'), ObjectId('69b57f7bf97ba72a25a2b9da'), ObjectId('69b57f7bf97ba72a25a2b9db'), ObjectId('69b57f7bf97ba72a25a2b9dc'), ObjectId('69b57f7bf97ba72a25a2b9dd'), ObjectId('69b57f7bf97ba72a25a2b9de'), ObjectId('69b57f7bf97ba72a25a2b9df'), ObjectId('69b57f7bf97ba72a25a2b9e0'), ObjectId('69b57f7bf97ba72a25a2b9e1'), ObjectId('69b57f7bf97ba72a25a2b9e2'), ObjectId('69b57f7bf97ba72a25a2b9e3'), ObjectId('69b57f7bf97ba72a25a2b9e4'), ObjectId('69b57f7bf97ba72a25a2b9e5'), ObjectId('69b57f7bf97ba72a25a2b9e6'), ObjectId('69b57f7bf97ba72a25a2b9e7'), ObjectId('69b57f7bf97ba72a25a2b9e8'), ObjectId('69b57f7bf97ba72a25a2b9e9'), ObjectId('69b57f7bf97ba72a25a2b9ea'), ObjectId('69b57f7bf97ba72a25a2b9eb'), ObjectId('69b57f7bf97ba72a25a2b9ec'), ObjectId('69b57f7bf97ba72a25a2b9ed'), ObjectId('69b57f7bf97ba72a25a2b9ee'), ObjectId('69b57f7bf97ba72a25a2b9ef'), ObjectId('69b57f7bf97ba72a25a2b9f0'), ObjectId('69b57f7bf97ba72a25a2b9f1'), ObjectId('69b57f7bf97ba72a25a2b9f2'), ObjectId('69b57f7bf97ba72a25a2b9f3'), ObjectId('69b57f7bf97ba72a25a2b9f4'), ObjectId('69b57f7bf97ba72a25a2b9f5'), ObjectId('69b57f7bf97ba72a25a2b9f6'), ObjectId('69b57f7bf97ba72a25a2b9f7'), ObjectId('69b57f7bf97ba72a25a2b9f8'), ObjectId('69b57f7bf97ba72a25a2b9f9'), ObjectId('69b57f7bf97ba72a25a2b9fa'), ObjectId('69b57f7bf97ba72a25a2b9fb'), ObjectId('69b57f7bf97ba72a25a2b9fc'), ObjectId('69b57f7bf97ba72a25a2b9fd'), ObjectId('69b57f7bf97ba72a25a2b9fe'), ObjectId('69b57f7bf97ba72a25a2b9ff'), ObjectId('69b57f7bf97ba72a25a2ba00'), ObjectId('69b57f7bf97ba72a25a2ba01'), ObjectId('69b57f7bf97ba72a25a2ba02'), ObjectId('69b57f7bf97ba72a25a2ba03'), ObjectId('69b57f7bf97ba72a25a2ba04'), ObjectId('69b57f7bf97ba72a25a2ba05'), ObjectId('69b57f7bf97ba72a25a2ba06'), ObjectId('69b57f7bf97ba72a25a2ba07'), ObjectId('69b57f7bf97ba72a25a2ba08'), ObjectId('69b57f7bf97ba72a25a2ba09'), ObjectId('69b57f7bf97ba72a25a2ba0a'), ObjectId('69b57f7bf97ba72a25a2ba0b'), ObjectId('69b57f7bf97ba72a25a2ba0c'), ObjectId('69b57f7bf97ba72a25a2ba0d'), ObjectId('69b57f7bf97ba72a25a2ba0e'), ObjectId('69b57f7bf97ba72a25a2ba0f'), ObjectId('69b57f7bf97ba72a25a2ba10'), ObjectId('69b57f7bf97ba72a25a2ba11'), ObjectId('69b57f7bf97ba72a25a2ba12'), ObjectId('69b57f7bf97ba72a25a2ba13'), ObjectId('69b57f7bf97ba72a25a2ba14'), ObjectId('69b57f7bf97ba72a25a2ba15'), ObjectId('69b57f7bf97ba72a25a2ba16'), ObjectId('69b57f7bf97ba72a25a2ba17'), ObjectId('69b57f7bf97ba72a25a2ba18'), ObjectId('69b57f7bf97ba72a25a2ba19'), ObjectId('69b57f7bf97ba72a25a2ba1a'), ObjectId('69b57f7bf97ba72a25a2ba1b'), ObjectId('69b57f7bf97ba72a25a2ba1c'), ObjectId('69b57f7bf97ba72a25a2ba1d'), ObjectId('69b57f7bf97ba72a25a2ba1e'), ObjectId('69b57f7bf97ba72a25a2ba1f'), ObjectId('69b57f7bf97ba72a25a2ba20'), ObjectId('69b57f7bf97ba72a25a2ba21'), ObjectId('69b57f7bf97ba72a25a2ba22'), ObjectId('69b57f7bf97ba72a25a2ba23'), ObjectId('69b57f7bf97ba72a25a2ba24'), ObjectId('69b57f7bf97ba72a25a2ba25'), ObjectId('69b57f7bf97ba72a25a2ba26'), ObjectId('69b57f7bf97ba72a25a2ba27'), ObjectId('69b57f7bf97ba72a25a2ba28'), ObjectId('69b57f7bf97ba72a25a2ba29'), ObjectId('69b57f7bf97ba72a25a2ba2a'), ObjectId('69b57f7bf97ba72a25a2ba2b'), ObjectId('69b57f7bf97ba72a25a2ba2c'), ObjectId('69b57f7bf97ba72a25a2ba2d'), ObjectId('69b57f7bf97ba72a25a2ba2e'), ObjectId('69b57f7bf97ba72a25a2ba2f'), ObjectId('69b57f7bf97ba72a25a2ba30'), ObjectId('69b57f7bf97ba72a25a2ba31'), ObjectId('69b57f7bf97ba72a25a2ba32'), ObjectId('69b57f7bf97ba72a25a2ba33'), ObjectId('69b57f7bf97ba72a25a2ba34'), ObjectId('69b57f7bf97ba72a25a2ba35'), ObjectId('69b57f7bf97ba72a25a2ba36'), ObjectId('69b57f7bf97ba72a25a2ba37'), ObjectId('69b57f7bf97ba72a25a2ba38'), ObjectId('69b57f7bf97ba72a25a2ba39'), ObjectId('69b57f7bf97ba72a25a2ba3a'), ObjectId('69b57f7bf97ba72a25a2ba3b'), ObjectId('69b57f7bf97ba72a25a2ba3c'), ObjectId('69b57f7bf97ba72a25a2ba3d'), ObjectId('69b57f7bf97ba72a25a2ba3e'), ObjectId('69b57f7bf97ba72a25a2ba3f'), ObjectId('69b57f7bf97ba72a25a2ba40'), ObjectId('69b57f7bf97ba72a25a2ba41'), ObjectId('69b57f7bf97ba72a25a2ba42'), ObjectId('69b57f7bf97ba72a25a2ba43'), ObjectId('69b57f7bf97ba72a25a2ba44'), ObjectId('69b57f7bf97ba72a25a2ba45'), ObjectId('69b57f7bf97ba72a25a2ba46'), ObjectId('69b57f7bf97ba72a25a2ba47'), ObjectId('69b57f7bf97ba72a25a2ba48'), ObjectId('69b57f7bf97ba72a25a2ba49'), ObjectId('69b57f7bf97ba72a25a2ba4a'), ObjectId('69b57f7bf97ba72a25a2ba4b'), ObjectId('69b57f7bf97ba72a25a2ba4c'), ObjectId('69b57f7bf97ba72a25a2ba4d'), ObjectId('69b57f7bf97ba72a25a2ba4e'), ObjectId('69b57f7bf97ba72a25a2ba4f'), ObjectId('69b57f7bf97ba72a25a2ba50'), ObjectId('69b57f7bf97ba72a25a2ba51'), ObjectId('69b57f7bf97ba72a25a2ba52'), ObjectId('69b57f7bf97ba72a25a2ba53'), ObjectId('69b57f7bf97ba72a25a2ba54'), ObjectId('69b57f7bf97ba72a25a2ba55'), ObjectId('69b57f7bf97ba72a25a2ba56'), ObjectId('69b57f7bf97ba72a25a2ba57'), ObjectId('69b57f7bf97ba72a25a2ba58'), ObjectId('69b57f7bf97ba72a25a2ba59'), ObjectId('69b57f7bf97ba72a25a2ba5a'), ObjectId('69b57f7bf97ba72a25a2ba5b'), ObjectId('69b57f7bf97ba72a25a2ba5c'), ObjectId('69b57f7bf97ba72a25a2ba5d'), ObjectId('69b57f7bf97ba72a25a2ba5e'), ObjectId('69b57f7bf97ba72a25a2ba5f'), ObjectId('69b57f7bf97ba72a25a2ba60'), ObjectId('69b57f7bf97ba72a25a2ba61'), ObjectId('69b57f7bf97ba72a25a2ba62'), ObjectId('69b57f7bf97ba72a25a2ba63'), ObjectId('69b57f7bf97ba72a25a2ba64'), ObjectId('69b57f7bf97ba72a25a2ba65'), ObjectId('69b57f7bf97ba72a25a2ba66'), ObjectId('69b57f7bf97ba72a25a2ba67'), ObjectId('69b57f7bf97ba72a25a2ba68'), ObjectId('69b57f7bf97ba72a25a2ba69'), ObjectId('69b57f7bf97ba72a25a2ba6a'), ObjectId('69b57f7bf97ba72a25a2ba6b'), ObjectId('69b57f7bf97ba72a25a2ba6c'), ObjectId('69b57f7bf97ba72a25a2ba6d'), ObjectId('69b57f7bf97ba72a25a2ba6e'), ObjectId('69b57f7bf97ba72a25a2ba6f'), ObjectId('69b57f7bf97ba72a25a2ba70'), ObjectId('69b57f7bf97ba72a25a2ba71'), ObjectId('69b57f7bf97ba72a25a2ba72'), ObjectId('69b57f7bf97ba72a25a2ba73'), ObjectId('69b57f7bf97ba72a25a2ba74'), ObjectId('69b57f7bf97ba72a25a2ba75'), ObjectId('69b57f7bf97ba72a25a2ba76'), ObjectId('69b57f7bf97ba72a25a2ba77'), ObjectId('69b57f7bf97ba72a25a2ba78'), ObjectId('69b57f7bf97ba72a25a2ba79'), ObjectId('69b57f7bf97ba72a25a2ba7a'), ObjectId('69b57f7bf97ba72a25a2ba7b'), ObjectId('69b57f7bf97ba72a25a2ba7c'), ObjectId('69b57f7bf97ba72a25a2ba7d'), ObjectId('69b57f7bf97ba72a25a2ba7e'), ObjectId('69b57f7bf97ba72a25a2ba7f'), ObjectId('69b57f7bf97ba72a25a2ba80'), ObjectId('69b57f7bf97ba72a25a2ba81'), ObjectId('69b57f7bf97ba72a25a2ba82'), ObjectId('69b57f7bf97ba72a25a2ba83'), ObjectId('69b57f7bf97ba72a25a2ba84'), ObjectId('69b57f7bf97ba72a25a2ba85'), ObjectId('69b57f7bf97ba72a25a2ba86'), ObjectId('69b57f7bf97ba72a25a2ba87'), ObjectId('69b57f7bf97ba72a25a2ba88'), ObjectId('69b57f7bf97ba72a25a2ba89'), ObjectId('69b57f7bf97ba72a25a2ba8a'), ObjectId('69b57f7bf97ba72a25a2ba8b'), ObjectId('69b57f7bf97ba72a25a2ba8c'), ObjectId('69b57f7bf97ba72a25a2ba8d'), ObjectId('69b57f7bf97ba72a25a2ba8e'), ObjectId('69b57f7bf97ba72a25a2ba8f'), ObjectId('69b57f7bf97ba72a25a2ba90'), ObjectId('69b57f7bf97ba72a25a2ba91'), ObjectId('69b57f7bf97ba72a25a2ba92'), ObjectId('69b57f7bf97ba72a25a2ba93'), ObjectId('69b57f7bf97ba72a25a2ba94'), ObjectId('69b57f7bf97ba72a25a2ba95'), ObjectId('69b57f7bf97ba72a25a2ba96'), ObjectId('69b57f7bf97ba72a25a2ba97'), ObjectId('69b57f7bf97ba72a25a2ba98'), ObjectId('69b57f7bf97ba72a25a2ba99'), ObjectId('69b57f7bf97ba72a25a2ba9a'), ObjectId('69b57f7bf97ba72a25a2ba9b'), ObjectId('69b57f7bf97ba72a25a2ba9c'), ObjectId('69b57f7bf97ba72a25a2ba9d'), ObjectId('69b57f7bf97ba72a25a2ba9e'), ObjectId('69b57f7bf97ba72a25a2ba9f'), ObjectId('69b57f7bf97ba72a25a2baa0'), ObjectId('69b57f7bf97ba72a25a2baa1'), ObjectId('69b57f7bf97ba72a25a2baa2'), ObjectId('69b57f7bf97ba72a25a2baa3'), ObjectId('69b57f7bf97ba72a25a2baa4'), ObjectId('69b57f7bf97ba72a25a2baa5'), ObjectId('69b57f7bf97ba72a25a2baa6'), ObjectId('69b57f7bf97ba72a25a2baa7'), ObjectId('69b57f7bf97ba72a25a2baa8'), ObjectId('69b57f7bf97ba72a25a2baa9'), ObjectId('69b57f7bf97ba72a25a2baaa'), ObjectId('69b57f7bf97ba72a25a2baab'), ObjectId('69b57f7bf97ba72a25a2baac'), ObjectId('69b57f7bf97ba72a25a2baad'), ObjectId('69b57f7bf97ba72a25a2baae'), ObjectId('69b57f7bf97ba72a25a2baaf'), ObjectId('69b57f7bf97ba72a25a2bab0'), ObjectId('69b57f7bf97ba72a25a2bab1'), ObjectId('69b57f7bf97ba72a25a2bab2'), ObjectId('69b57f7bf97ba72a25a2bab3'), ObjectId('69b57f7bf97ba72a25a2bab4'), ObjectId('69b57f7bf97ba72a25a2bab5'), ObjectId('69b57f7bf97ba72a25a2bab6'), ObjectId('69b57f7bf97ba72a25a2bab7'), ObjectId('69b57f7bf97ba72a25a2bab8'), ObjectId('69b57f7bf97ba72a25a2bab9'), ObjectId('69b57f7bf97ba72a25a2baba'), ObjectId('69b57f7bf97ba72a25a2babb'), ObjectId('69b57f7bf97ba72a25a2babc'), ObjectId('69b57f7bf97ba72a25a2babd'), ObjectId('69b57f7bf97ba72a25a2babe'), ObjectId('69b57f7bf97ba72a25a2babf'), ObjectId('69b57f7bf97ba72a25a2bac0'), ObjectId('69b57f7bf97ba72a25a2bac1'), ObjectId('69b57f7bf97ba72a25a2bac2'), ObjectId('69b57f7bf97ba72a25a2bac3'), ObjectId('69b57f7bf97ba72a25a2bac4'), ObjectId('69b57f7bf97ba72a25a2bac5'), ObjectId('69b57f7bf97ba72a25a2bac6'), ObjectId('69b57f7bf97ba72a25a2bac7'), ObjectId('69b57f7bf97ba72a25a2bac8'), ObjectId('69b57f7bf97ba72a25a2bac9'), ObjectId('69b57f7bf97ba72a25a2baca'), ObjectId('69b57f7bf97ba72a25a2bacb'), ObjectId('69b57f7bf97ba72a25a2bacc'), ObjectId('69b57f7bf97ba72a25a2bacd'), ObjectId('69b57f7bf97ba72a25a2bace'), ObjectId('69b57f7bf97ba72a25a2bacf'), ObjectId('69b57f7bf97ba72a25a2bad0'), ObjectId('69b57f7bf97ba72a25a2bad1'), ObjectId('69b57f7bf97ba72a25a2bad2'), ObjectId('69b57f7bf97ba72a25a2bad3'), ObjectId('69b57f7bf97ba72a25a2bad4'), ObjectId('69b57f7bf97ba72a25a2bad5'), ObjectId('69b57f7bf97ba72a25a2bad6'), ObjectId('69b57f7bf97ba72a25a2bad7'), ObjectId('69b57f7bf97ba72a25a2bad8'), ObjectId('69b57f7bf97ba72a25a2bad9'), ObjectId('69b57f7bf97ba72a25a2bada'), ObjectId('69b57f7bf97ba72a25a2badb'), ObjectId('69b57f7bf97ba72a25a2badc'), ObjectId('69b57f7bf97ba72a25a2badd'), ObjectId('69b57f7bf97ba72a25a2bade'), ObjectId('69b57f7bf97ba72a25a2badf'), ObjectId('69b57f7bf97ba72a25a2bae0'), ObjectId('69b57f7bf97ba72a25a2bae1'), ObjectId('69b57f7bf97ba72a25a2bae2'), ObjectId('69b57f7bf97ba72a25a2bae3'), ObjectId('69b57f7bf97ba72a25a2bae4'), ObjectId('69b57f7bf97ba72a25a2bae5'), ObjectId('69b57f7bf97ba72a25a2bae6'), ObjectId('69b57f7bf97ba72a25a2bae7'), ObjectId('69b57f7bf97ba72a25a2bae8'), ObjectId('69b57f7bf97ba72a25a2bae9'), ObjectId('69b57f7bf97ba72a25a2baea'), ObjectId('69b57f7bf97ba72a25a2baeb'), ObjectId('69b57f7bf97ba72a25a2baec'), ObjectId('69b57f7bf97ba72a25a2baed'), ObjectId('69b57f7bf97ba72a25a2baee'), ObjectId('69b57f7bf97ba72a25a2baef'), ObjectId('69b57f7bf97ba72a25a2baf0'), ObjectId('69b57f7bf97ba72a25a2baf1'), ObjectId('69b57f7bf97ba72a25a2baf2'), ObjectId('69b57f7bf97ba72a25a2baf3'), ObjectId('69b57f7bf97ba72a25a2baf4'), ObjectId('69b57f7bf97ba72a25a2baf5'), ObjectId('69b57f7bf97ba72a25a2baf6'), ObjectId('69b57f7bf97ba72a25a2baf7'), ObjectId('69b57f7bf97ba72a25a2baf8'), ObjectId('69b57f7bf97ba72a25a2baf9'), ObjectId('69b57f7bf97ba72a25a2bafa'), ObjectId('69b57f7bf97ba72a25a2bafb'), ObjectId('69b57f7bf97ba72a25a2bafc'), ObjectId('69b57f7bf97ba72a25a2bafd'), ObjectId('69b57f7bf97ba72a25a2bafe'), ObjectId('69b57f7bf97ba72a25a2baff'), ObjectId('69b57f7bf97ba72a25a2bb00'), ObjectId('69b57f7bf97ba72a25a2bb01'), ObjectId('69b57f7bf97ba72a25a2bb02'), ObjectId('69b57f7bf97ba72a25a2bb03'), ObjectId('69b57f7bf97ba72a25a2bb04'), ObjectId('69b57f7bf97ba72a25a2bb05'), ObjectId('69b57f7bf97ba72a25a2bb06'), ObjectId('69b57f7bf97ba72a25a2bb07'), ObjectId('69b57f7bf97ba72a25a2bb08'), ObjectId('69b57f7bf97ba72a25a2bb09'), ObjectId('69b57f7bf97ba72a25a2bb0a'), ObjectId('69b57f7bf97ba72a25a2bb0b'), ObjectId('69b57f7bf97ba72a25a2bb0c'), ObjectId('69b57f7bf97ba72a25a2bb0d'), ObjectId('69b57f7bf97ba72a25a2bb0e'), ObjectId('69b57f7bf97ba72a25a2bb0f'), ObjectId('69b57f7bf97ba72a25a2bb10'), ObjectId('69b57f7bf97ba72a25a2bb11'), ObjectId('69b57f7bf97ba72a25a2bb12'), ObjectId('69b57f7bf97ba72a25a2bb13'), ObjectId('69b57f7bf97ba72a25a2bb14'), ObjectId('69b57f7bf97ba72a25a2bb15'), ObjectId('69b57f7bf97ba72a25a2bb16'), ObjectId('69b57f7bf97ba72a25a2bb17'), ObjectId('69b57f7bf97ba72a25a2bb18'), ObjectId('69b57f7bf97ba72a25a2bb19'), ObjectId('69b57f7bf97ba72a25a2bb1a'), ObjectId('69b57f7bf97ba72a25a2bb1b'), ObjectId('69b57f7bf97ba72a25a2bb1c'), ObjectId('69b57f7bf97ba72a25a2bb1d'), ObjectId('69b57f7bf97ba72a25a2bb1e'), ObjectId('69b57f7bf97ba72a25a2bb1f'), ObjectId('69b57f7bf97ba72a25a2bb20'), ObjectId('69b57f7bf97ba72a25a2bb21'), ObjectId('69b57f7bf97ba72a25a2bb22'), ObjectId('69b57f7bf97ba72a25a2bb23'), ObjectId('69b57f7bf97ba72a25a2bb24'), ObjectId('69b57f7bf97ba72a25a2bb25'), ObjectId('69b57f7bf97ba72a25a2bb26'), ObjectId('69b57f7bf97ba72a25a2bb27'), ObjectId('69b57f7bf97ba72a25a2bb28'), ObjectId('69b57f7bf97ba72a25a2bb29'), ObjectId('69b57f7bf97ba72a25a2bb2a'), ObjectId('69b57f7bf97ba72a25a2bb2b'), ObjectId('69b57f7bf97ba72a25a2bb2c'), ObjectId('69b57f7bf97ba72a25a2bb2d'), ObjectId('69b57f7bf97ba72a25a2bb2e'), ObjectId('69b57f7bf97ba72a25a2bb2f'), ObjectId('69b57f7bf97ba72a25a2bb30'), ObjectId('69b57f7bf97ba72a25a2bb31'), ObjectId('69b57f7bf97ba72a25a2bb32'), ObjectId('69b57f7bf97ba72a25a2bb33'), ObjectId('69b57f7bf97ba72a25a2bb34'), ObjectId('69b57f7bf97ba72a25a2bb35'), ObjectId('69b57f7bf97ba72a25a2bb36'), ObjectId('69b57f7bf97ba72a25a2bb37'), ObjectId('69b57f7bf97ba72a25a2bb38'), ObjectId('69b57f7bf97ba72a25a2bb39'), ObjectId('69b57f7bf97ba72a25a2bb3a'), ObjectId('69b57f7bf97ba72a25a2bb3b'), ObjectId('69b57f7bf97ba72a25a2bb3c'), ObjectId('69b57f7bf97ba72a25a2bb3d'), ObjectId('69b57f7bf97ba72a25a2bb3e'), ObjectId('69b57f7bf97ba72a25a2bb3f'), ObjectId('69b57f7bf97ba72a25a2bb40'), ObjectId('69b57f7bf97ba72a25a2bb41'), ObjectId('69b57f7bf97ba72a25a2bb42'), ObjectId('69b57f7bf97ba72a25a2bb43'), ObjectId('69b57f7bf97ba72a25a2bb44'), ObjectId('69b57f7bf97ba72a25a2bb45'), ObjectId('69b57f7bf97ba72a25a2bb46'), ObjectId('69b57f7bf97ba72a25a2bb47'), ObjectId('69b57f7bf97ba72a25a2bb48'), ObjectId('69b57f7bf97ba72a25a2bb49'), ObjectId('69b57f7bf97ba72a25a2bb4a'), ObjectId('69b57f7bf97ba72a25a2bb4b'), ObjectId('69b57f7bf97ba72a25a2bb4c'), ObjectId('69b57f7bf97ba72a25a2bb4d'), ObjectId('69b57f7bf97ba72a25a2bb4e'), ObjectId('69b57f7bf97ba72a25a2bb4f'), ObjectId('69b57f7bf97ba72a25a2bb50'), ObjectId('69b57f7bf97ba72a25a2bb51'), ObjectId('69b57f7bf97ba72a25a2bb52'), ObjectId('69b57f7bf97ba72a25a2bb53'), ObjectId('69b57f7bf97ba72a25a2bb54'), ObjectId('69b57f7bf97ba72a25a2bb55'), ObjectId('69b57f7bf97ba72a25a2bb56'), ObjectId('69b57f7bf97ba72a25a2bb57'), ObjectId('69b57f7bf97ba72a25a2bb58'), ObjectId('69b57f7bf97ba72a25a2bb59'), ObjectId('69b57f7bf97ba72a25a2bb5a'), ObjectId('69b57f7bf97ba72a25a2bb5b'), ObjectId('69b57f7bf97ba72a25a2bb5c'), ObjectId('69b57f7bf97ba72a25a2bb5d'), ObjectId('69b57f7bf97ba72a25a2bb5e'), ObjectId('69b57f7bf97ba72a25a2bb5f'), ObjectId('69b57f7bf97ba72a25a2bb60'), ObjectId('69b57f7bf97ba72a25a2bb61'), ObjectId('69b57f7bf97ba72a25a2bb62'), ObjectId('69b57f7bf97ba72a25a2bb63'), ObjectId('69b57f7bf97ba72a25a2bb64'), ObjectId('69b57f7bf97ba72a25a2bb65'), ObjectId('69b57f7bf97ba72a25a2bb66'), ObjectId('69b57f7bf97ba72a25a2bb67'), ObjectId('69b57f7bf97ba72a25a2bb68'), ObjectId('69b57f7bf97ba72a25a2bb69'), ObjectId('69b57f7bf97ba72a25a2bb6a'), ObjectId('69b57f7bf97ba72a25a2bb6b'), ObjectId('69b57f7bf97ba72a25a2bb6c'), ObjectId('69b57f7bf97ba72a25a2bb6d'), ObjectId('69b57f7bf97ba72a25a2bb6e'), ObjectId('69b57f7bf97ba72a25a2bb6f'), ObjectId('69b57f7bf97ba72a25a2bb70'), ObjectId('69b57f7bf97ba72a25a2bb71'), ObjectId('69b57f7bf97ba72a25a2bb72'), ObjectId('69b57f7bf97ba72a25a2bb73'), ObjectId('69b57f7bf97ba72a25a2bb74'), ObjectId('69b57f7bf97ba72a25a2bb75'), ObjectId('69b57f7bf97ba72a25a2bb76'), ObjectId('69b57f7bf97ba72a25a2bb77'), ObjectId('69b57f7bf97ba72a25a2bb78'), ObjectId('69b57f7bf97ba72a25a2bb79'), ObjectId('69b57f7bf97ba72a25a2bb7a'), ObjectId('69b57f7bf97ba72a25a2bb7b'), ObjectId('69b57f7bf97ba72a25a2bb7c'), ObjectId('69b57f7bf97ba72a25a2bb

In [20]:
collection.find_one()

{'_id': ObjectId('69b57f7bf97ba72a25a2b970'),
 'ID': 1000002330,
 'name': 'The Songs of Adelaide & Abullah',
 'category': 'Poetry',
 'main_category': 'Publishing',
 'currency': 'GBP',
 'deadline': datetime.datetime(2015, 10, 9, 0, 0),
 'goal': 1000.0,
 'launched': datetime.datetime(2015, 8, 11, 12, 12, 28),
 'pledged': 0.0,
 'state': 'failed',
 'backers': 0.0,
 'country': 'GB',
 'usd pledged': 0.0,
 'usd_pledged_real': 0.0,
 'usd_goal_real': 1533.95,
 'CampaignDuration': 58,
 'FundingRatio': 0.0,
 'GoalCategory': 'Low Goal',
 'LaunchMonth': 'August'}

In [21]:
pipeline = [
    {
        "$group": {
            "_id": "$main_category",
            "total_projects": {"$sum": 1},
            "successful_projects": {
                "$sum": {
                    "$cond": [{"$eq": ["$state", "successful"]}, 1, 0]
                }
            }
        }
    },
    {
        "$project": {
            "success_rate": {
                "$multiply": [
                    {"$divide": ["$successful_projects", "$total_projects"]},
                    100
                ]
            }
        }
    }
]

list(collection.aggregate(pipeline))

[{'_id': 'Art', 'success_rate': 40.68530917684128},
 {'_id': 'Photography', 'success_rate': 30.96446700507614},
 {'_id': 'Journalism', 'success_rate': 20.0},
 {'_id': 'Crafts', 'success_rate': 23.838630806845966},
 {'_id': 'Food', 'success_rate': 26.592282659228268},
 {'_id': 'Technology', 'success_rate': 21.281699794379712},
 {'_id': 'Fashion', 'success_rate': 25.326633165829143},
 {'_id': 'Comics', 'success_rate': 55.94758064516129},
 {'_id': 'Publishing', 'success_rate': 30.889903023388477},
 {'_id': 'Design', 'success_rate': 34.276018099547514},
 {'_id': 'Games', 'success_rate': 36.45569620253165},
 {'_id': 'Film & Video', 'success_rate': 38.48190644307149},
 {'_id': 'Music', 'success_rate': 49.66917636322154},
 {'_id': 'Theater', 'success_rate': 60.51844466600199},
 {'_id': 'Dance', 'success_rate': 58.77192982456141}]

In [22]:
pipeline = [
    {
        "$group": {
            "_id": "$country",
            "avg_pledged": {"$avg": "$usd_pledged_real"}
        }
    },
    {"$sort": {"avg_pledged": -1}}
]

list(collection.aggregate(pipeline))

[{'_id': 'NL', 'avg_pledged': 27129.41474137931},
 {'_id': 'CH', 'avg_pledged': 18617.276140350878},
 {'_id': 'HK', 'avg_pledged': 14232.12393442623},
 {'_id': 'SG', 'avg_pledged': 12841.503953488373},
 {'_id': 'DE', 'avg_pledged': 12077.66331378299},
 {'_id': 'US', 'avg_pledged': 9817.564192760043},
 {'_id': 'SE', 'avg_pledged': 8611.653846153846},
 {'_id': 'FR', 'avg_pledged': 8461.417111111112},
 {'_id': 'IE', 'avg_pledged': 7854.023108108107},
 {'_id': 'NZ', 'avg_pledged': 6259.603652173913},
 {'_id': 'ES', 'avg_pledged': 6246.877512437811},
 {'_id': 'GB', 'avg_pledged': 6017.339114257491},
 {'_id': 'AT', 'avg_pledged': 5847.675},
 {'_id': 'AU', 'avg_pledged': 5710.651413843888},
 {'_id': 'CA', 'avg_pledged': 5616.146694656489},
 {'_id': 'IT', 'avg_pledged': 4354.195551601423},
 {'_id': 'DK', 'avg_pledged': 4197.425730337079},
 {'_id': 'LU', 'avg_pledged': 3116.5666666666666},
 {'_id': 'BE', 'avg_pledged': 2453.8892424242426},
 {'_id': 'NO', 'avg_pledged': 2402.579178082192},
 {'_id': 'MX', 'avg_pledged': 863.9916883116883},
 {'_id': 'JP', 'avg_pledged': 290.6433333333334}]

In [23]:
pipeline = [
    {"$sort": {"FundingRatio": -1}},
    {"$limit": 5},
    {
        "$project": {
            "name": 1,
            "FundingRatio": 1,
            "usd_goal_real": 1,
            "usd_pledged_real": 1
        }
    }
]

list(collection.aggregate(pipeline))

[{'_id': ObjectId('69b57f7bf97ba72a25a2f40d'),
  'name': "THE 'mi8' RISES | The Best Wireless Duo Stereo Sound System",
  'usd_pledged_real': 22603.0,
  'usd_goal_real': 1.0,
  'FundingRatio': 22603.0},
 {'_id': ObjectId('69b57f7bf97ba72a25a3233a'),
  'name': 'Arduino IoT. Home automation, 3D printing, robotics & more!',
  'usd_pledged_real': 9605.0,
  'usd_goal_real': 1.0,
  'FundingRatio': 9605.0},
 {'_id': ObjectId('69b57f7bf97ba72a25a2f780'),
  'name': "$9 Clearest Phone Hologram (Pepper's Ghost Pyramid)",
  'usd_pledged_real': 5782.25,
  'usd_goal_real': 0.75,
  'FundingRatio': 7709.666666666667},
 {'_id': ObjectId('69b57f7bf97ba72a25a2e011'),
  'name': 'LENDEMAIN DE VEILLE',
  'usd_pledged_real': 3978.02,
  'usd_goal_real': 0.75,
  'FundingRatio': 5304.026666666667},
 {'_id': ObjectId('69b57f7bf97ba72a25a2cbef'),
  'name': 'The $1 Play What You Want Mystery Campaign RPG Project',
  'usd_pledged_real': 4773.91,
  'usd_goal_real': 1.0,
  'FundingRatio': 4773.91}]

In [24]:
pipeline = [
    {"$match": {"state": "failed"}},
    {
        "$group": {
            "_id": "$category",
            "failures": {"$sum": 1}
        }
    },
    {"$sort": {"failures": -1}},
    {"$limit": 1}
]

list(collection.aggregate(pipeline))

[{'_id': 'Product Design', 'failures': 958}]

In [25]:
pipeline = [
    {
        "$group": {
            "_id": "$state",
            "avg_duration": {"$avg": "$CampaignDuration"}
        }
    }
]

list(collection.aggregate(pipeline))

[{'_id': 'successful', 'avg_duration': 31.042306744434406},
 {'_id': 'failed', 'avg_duration': 34.37304588295051},
 {'_id': 'suspended', 'avg_duration': 35.50632911392405},
 {'_id': 'canceled', 'avg_duration': 39.226152507973325}]

In [26]:
pipeline = [
    {"$match": {"state": "successful"}},
    {
        "$group": {
            "_id": "$LaunchMonth",
            "successful_projects": {"$sum": 1}
        }
    },
    {"$sort": {"successful_projects": -1}},
    {"$limit": 1}
]

list(collection.aggregate(pipeline))

[{'_id': 'May', 'successful_projects': 1120}]

In [27]:
pipeline = [
    {
        "$group": {
            "_id": "$main_category",
            "avg_backers": {"$avg": "$backers"}
        }
    }
]

list(collection.aggregate(pipeline))

[{'_id': 'Design', 'avg_backers': 229.42986425339367},
 {'_id': 'Games', 'avg_backers': 338.2003164556962},
 {'_id': 'Theater', 'avg_backers': 44.94616151545364},
 {'_id': 'Film & Video', 'avg_backers': 58.98676081200353},
 {'_id': 'Music', 'avg_backers': 52.91079169518594},
 {'_id': 'Crafts', 'avg_backers': 28.597799511002446},
 {'_id': 'Technology', 'avg_backers': 148.17580534612748},
 {'_id': 'Food', 'avg_backers': 63.89121338912134},
 {'_id': 'Dance', 'avg_backers': 46.76608187134503},
 {'_id': 'Art', 'avg_backers': 40.5494289090193},
 {'_id': 'Photography', 'avg_backers': 42.028426395939086},
 {'_id': 'Journalism', 'avg_backers': 39.79240506329114},
 {'_id': 'Comics', 'avg_backers': 140.27520161290323},
 {'_id': 'Publishing', 'avg_backers': 50.32373074729036},
 {'_id': 'Fashion', 'avg_backers': 70.82663316582915}]

In [28]:
pipeline = [
    {
        "$group": {
            "_id": None,
            "total_projects": {"$sum": 1},
            "reached_goal": {
                "$sum": {
                    "$cond": [{"$gte": ["$FundingRatio", 1]}, 1, 0]
                }
            }
        }
    },
    {
        "$project": {
            "percentage_reached_goal": {
                "$multiply": [
                    {"$divide": ["$reached_goal", "$total_projects"]},
                    100
                ]
            }
        }
    }
]

list(collection.aggregate(pipeline))

[{'_id': None, 'percentage_reached_goal': 36.616018388608616}]

MongoDB Schema Design Justification

MongoDB follows a document-based model, so each Kickstarter project is stored as a single JSON document containing all attributes of the project. This design was chosen because the dataset naturally represents projects as independent records with multiple related fields such as category, goal, pledged amount, and campaign duration.

Storing the entire project in one document avoids joins and allows flexible querying across different attributes. Since MongoDB supports dynamic schemas, it was convenient to store both the original dataset attributes and the engineered features (CampaignDuration, FundingRatio, GoalCategory, and LaunchMonth) together in the same document. This structure makes aggregation queries such as success rates, average pledged amounts, and campaign statistics efficient using MongoDB aggregation pipelines.